"""
Document Generation API — compliance document creation, management, and export.

This module provides endpoints for:
  - POST /documents/generate  : Generate AI compliance documents using LLM
  - GET  /documents/           : List all documents for the authenticated user
  - GET  /documents/{id}       : Retrieve a specific document
  - PATCH /documents/{id}      : Update document content or metadata
  - DELETE /documents/{id}     : Delete a document
  - GET  /documents/{id}/pdf   : Export document as PDF
  - POST /documents/{id}/share : Generate a shareable link for a document

Dependencies:
  - reportlab  : PDF generation
  - SQLAlchemy : ORM session for Document persistence
  - pydantic   : request/response schema validation
  - python-jose: JWT token for document sharing
"""
from datetime import datetime, timedelta, timezone

from fastapi import APIRouter, Depends, HTTPException, status, Query
from jose import jwt, JWTError
from jose.exceptions import ExpiredSignatureError


from fastapi.responses import FileResponse, StreamingResponse
from sqlalchemy.orm import Session
from typing import List
from io import BytesIO
from html import escape as html_escape
from urllib.parse import quote
import difflib
import re

from app.core.config import settings
from app.core.database import get_db
from app.core.security import get_current_user
from app.models.user import User
from app.models.ai_system import AISystem
from app.models.document import Document, DocumentVersion, DocumentType, DocumentStatus
from app.modules.llm.document_generator import generate_compliance_narrative
from app.schemas.document import (
    DocumentCreate,
    DocumentResponse,
    DocumentGenerateRequest,
    DocumentShareResponse,
    DocumentUpdateRequest,
    DocumentTemplateResponse,
    DocumentUpdateRequest,
    DocumentVersionResponse,
    DocumentVersionWithContent,
    DocumentDiffResponse,
    DiffHunk,
    DiffHunkLine,
)
from app.schemas.pagination import PaginatedResponse
from app.modules.llm.document_generator import generate_compliance_narrative

# PDF generation
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_LEFT, TA_CENTER


router = APIRouter()

def create_share_token(document_id: int):
    expire = datetime.now(timezone.utc) + timedelta(
        days=settings.DOCUMENT_SHARE_EXPIRE_DAYS
    )

    payload = {
        "document_id": document_id,
        "type": "document_share",
        "exp": expire
    }

    token = jwt.encode(
        payload,
        settings.SECRET_KEY,
        algorithm=settings.ALGORITHM
    )

    return token

def _escape_pdf_text(value: str) -> str:
    """Escape user-controlled text before ReportLab Paragraph parses it."""
    return html_escape(value, quote=False)


def _render_inline_markdown(value: str) -> str:
    """Render the small markdown subset supported by PDF export safely."""
    escaped = _escape_pdf_text(value.strip())
    return re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', escaped)


def _safe_pdf_filename(title: str) -> str:
    """Return a header-safe PDF filename derived from a document title."""
    filename = re.sub(r"[\x00-\x1f\x7f]", "", title or "").strip()
    filename = re.sub(r'[/\\:*?"<>|]+', "_", filename)
    filename = re.sub(r"\s+", " ", filename).strip(" ._")

    if not filename:
        filename = "document"

    return f"{filename[:120]}.pdf"


# Document templates for generation
DOCUMENT_TEMPLATES = {
    DocumentType.TECHNICAL_DOCUMENTATION: """
# Technical Documentation - {system_name}

## 1. General Description
**System Name:** {system_name}
**Version:** {version}
**Use Case:** {use_case}
**Sector:** {sector}

## 2. Intended Purpose
{description}

## 3. System Architecture
[Describe the overall architecture, components, and data flow]

## 4. Training Data
- Data sources used
- Data preprocessing steps
- Data quality measures

## 5. Model Information
- Algorithm/model type
- Training methodology
- Performance metrics

## 6. Input/Output Specifications
- Expected inputs
- Output format and interpretation

## 7. Limitations and Risks
- Known limitations
- Identified risks and mitigations

## 8. Human Oversight Measures
- Human-in-the-loop mechanisms
- Override capabilities

## 9. Logging and Monitoring
- What is logged
- Monitoring procedures

---
Generated by EU AI Act Compliance Tool
""",
    DocumentType.RISK_ASSESSMENT: """
# Risk Assessment Report - {system_name}

## Executive Summary
This document presents the risk assessment for {system_name}, an AI system used for {use_case}.

**Risk Level:** {risk_level}
**Assessment Date:** {date}

## 1. System Overview
{description}

## 2. Risk Classification
Based on EU AI Act criteria, this system is classified as **{risk_level}** risk.

### Classification Rationale
{classification_reasons}

## 3. Identified Risks

### 3.1 Data-Related Risks
- [ ] Data quality issues
- [ ] Bias in training data
- [ ] Privacy concerns

### 3.2 Model-Related Risks
- [ ] Accuracy limitations
- [ ] Robustness issues
- [ ] Explainability gaps

### 3.3 Deployment Risks
- [ ] Misuse potential
- [ ] Human oversight gaps
- [ ] Integration risks

## 4. Mitigation Measures
{recommendations}

## 5. Compliance Requirements
{requirements}

## 6. Next Steps
{next_steps}

---
Generated by EU AI Act Compliance Tool
""",
    DocumentType.CONFORMITY_DECLARATION: """
# EU Declaration of Conformity

## AI System Identification
**System Name:** {system_name}
**Version:** {version}
**Manufacturer/Provider:** {company_name}

## Declaration
We hereby declare that the AI system identified above has been designed and developed in conformity with the requirements of Regulation (EU) 2024/1689 (EU AI Act).

## Applicable Requirements
The following requirements have been addressed:

- [ ] Article 9 - Risk Management System
- [ ] Article 10 - Data and Data Governance
- [ ] Article 11 - Technical Documentation
- [ ] Article 12 - Record-keeping
- [ ] Article 13 - Transparency and Information
- [ ] Article 14 - Human Oversight
- [ ] Article 15 - Accuracy, Robustness, Cybersecurity

## Conformity Assessment
**Assessment Type:** Internal control (Annex VI)
**Date of Assessment:** {date}

## Responsible Person
**Name:** _______________
**Title:** _______________
**Date:** _______________
**Signature:** _______________

---
Generated by EU AI Act Compliance Tool
""",
    DocumentType.DATA_GOVERNANCE: """
# Data Governance Policy - {system_name}

## 1. Policy Scope
This policy defines data governance controls for {system_name}, an AI system used for {use_case} in the {sector} sector.

**System Version:** {version}
**Provider:** {company_name}
**Policy Date:** {date}

## 2. EU AI Act Article 10 Alignment
This policy supports data and data governance obligations under Article 10 of Regulation (EU) 2024/1689.

## 3. Data Quality Controls
- [ ] Define acceptance criteria for training, validation, and testing data
- [ ] Check datasets for completeness, accuracy, relevance, and representativeness
- [ ] Document known data gaps, limitations, and quality risks
- [ ] Review data quality before every material model or system update

## 4. Data Provenance and Lineage
- [ ] Record each dataset source, collection method, and lawful basis for use
- [ ] Maintain dataset version history and transformation records
- [ ] Track synthetic, inferred, or third-party data separately
- [ ] Keep evidence of data licenses, permissions, and provider assurances

## 5. Bias and Representativeness Review
- [ ] Assess whether datasets represent the intended user groups and operating context
- [ ] Identify potential bias across protected or sensitive characteristics
- [ ] Define mitigation steps for detected imbalance or discriminatory outcomes
- [ ] Reassess representativeness after deployment drift or scope changes

## 6. Retention and Disposal
- [ ] Define retention periods for source datasets, derived datasets, model inputs, and logs
- [ ] Restrict retention to documented compliance, safety, and audit needs
- [ ] Apply secure deletion or anonymization when data is no longer required
- [ ] Review retention schedules at least annually

## 7. Ownership and Review
The provider is responsible for maintaining this policy, reviewing it after significant system changes, and preserving evidence for competent authorities.

---
Generated by EU AI Act Compliance Tool
""",
    DocumentType.TRANSPARENCY_NOTICE: """
# Transparency Notice - {system_name}

## 1. Notice Purpose
This notice provides user-facing disclosure for {system_name}, an AI system used for {use_case} in the {sector} sector.

**Provider:** {company_name}
**System Version:** {version}
**Notice Date:** {date}

## 2. EU AI Act Article 50 Disclosure
This notice supports transparency obligations for limited risk AI systems under Article 50 of Regulation (EU) 2024/1689.

## 3. AI System Disclosure
Users should be informed when they are interacting with, or receiving outputs from, this AI system unless the AI nature is obvious from the context.

Suggested disclosure:
> You are interacting with an AI-enabled system. Its outputs may be automated and should be reviewed before being used for important decisions.

## 4. Intended Use
{description}

## 5. User Instructions
- Review AI-generated outputs before relying on them
- Do not provide unnecessary personal, confidential, or sensitive information
- Use the system only for its intended purpose
- Escalate unclear, harmful, or unexpected outputs to the provider contact

## 6. Limitations
- The system may produce incomplete, inaccurate, or context-dependent outputs
- Performance may vary across user groups, input quality, or deployment conditions
- Human review may be required for consequential or high-impact use cases

## 7. Contact and Feedback
Provider: {company_name}

Users may report concerns, request clarification, or provide feedback through the provider's established support channel.

---
Generated by EU AI Act Compliance Tool
""",
}


@router.post("/", response_model=DocumentResponse, status_code=status.HTTP_201_CREATED)
def create_document(
    doc_data: DocumentCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new document for the authenticated user."""
    if doc_data.ai_system_id is not None:
        ai_system = (
            db.query(AISystem)
            .filter(
                AISystem.id == doc_data.ai_system_id,
                AISystem.owner_id == current_user.id,
            )
            .first()
        )
        if not ai_system:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="AI system not found",
            )

    document = Document(
        owner_id=current_user.id,
        title=doc_data.title,
        document_type=doc_data.document_type,
        ai_system_id=doc_data.ai_system_id,
        content=doc_data.content,
    )
    db.add(document)
    db.commit()
    db.refresh(document)
    return document


@router.get("/", response_model=PaginatedResponse[DocumentResponse])
def list_documents(
    skip: int = Query(0, ge=0, description="Items to skip"),
    limit: int = Query(50, ge=1, le=100, description="Items per page"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """List the current user's documents with pagination."""
    base_query = db.query(Document).filter(Document.owner_id == current_user.id)
    total = base_query.count()

    documents = base_query.offset(skip).limit(limit).all()
    return PaginatedResponse(items=documents, total=total, skip=skip, limit=limit)


@router.get("/share/{token}", response_model=DocumentResponse)
def get_shared_document(
    token: str,
    db: Session = Depends(get_db)
):
    """Access shared document without authentication."""

    try:
        payload = jwt.decode(
            token,
            settings.SECRET_KEY,
            algorithms=[settings.ALGORITHM]
        )

    except ExpiredSignatureError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Share link expired"
        )

    except JWTError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid share token"
        )

    if payload.get("type") != "document_share":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token type"
        )

    document_id = payload.get("document_id")

    if not document_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid token payload"
        )

    document = db.query(Document).filter(
        Document.id == document_id
    ).first()

    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )

    if hasattr(document, "is_deleted") and document.is_deleted:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Share link revoked"
        )

    return document

@router.post(
    "/{document_id}/share",
    response_model=DocumentShareResponse
)
def share_document(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Generate share link for a document."""

    document = db.query(Document).filter(
        Document.id == document_id,
        Document.owner_id == current_user.id
    ).first()

    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )

    token = create_share_token(document.id)

    return {
        "share_url": f"/api/v1/documents/share/{token}",
        "expires_in_days": settings.DOCUMENT_SHARE_EXPIRE_DAYS
    }
@router.get("/templates", response_model=List[DocumentTemplateResponse])
def list_document_templates(
    current_user: User = Depends(get_current_user),
):
    """List available document templates for generation."""
    descriptions = {
        DocumentType.TECHNICAL_DOCUMENTATION: "Generate technical documentation for an AI system.",
        DocumentType.RISK_ASSESSMENT: "Generate a risk assessment report for an AI system.",
        DocumentType.CONFORMITY_DECLARATION: "Generate an EU declaration of conformity for an AI system.",
        DocumentType.DATA_GOVERNANCE: "Generate a data governance policy covering quality, provenance, and retention controls.",
        DocumentType.TRANSPARENCY_NOTICE: "Generate a user-facing transparency notice for limited risk AI systems.",
    }

    return [
        DocumentTemplateResponse(
            type=document_type,
            name=document_type.value.replace("_", " ").title(),
            description=descriptions[document_type],
        )
        for document_type in DOCUMENT_TEMPLATES.keys()
    ]


@router.get("/{document_id}", response_model=DocumentResponse)
def get_document(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Return a single document owned by the current user."""
    document = (
        db.query(Document)
        .filter(Document.id == document_id, Document.owner_id == current_user.id)
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Document not found"
        )
    return document

@router.get("/{document_id}/versions", response_model=list[DocumentVersionResponse])
def list_document_versions(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List all versions of a document."""
    doc = db.query(Document).filter(
        Document.id == document_id,
        Document.owner_id == current_user.id
    ).first()
    if not doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND)
    return db.query(DocumentVersion).filter(
        DocumentVersion.document_id == document_id
    ).order_by(DocumentVersion.created_at.asc()).all()


@router.get("/{document_id}/diff", response_model=DocumentDiffResponse)
def get_document_diff(
    document_id: int,
    v1: int = Query(..., description="First version ID"),
    v2: int = Query(..., description="Second version ID"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Compare two versions of a document and return a structured diff."""
    doc = db.query(Document).filter(
        Document.id == document_id,
        Document.owner_id == current_user.id
    ).first()
    if not doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND)

    ver1 = db.query(DocumentVersion).filter(
        DocumentVersion.id == v1,
        DocumentVersion.document_id == document_id,
    ).first()
    ver2 = db.query(DocumentVersion).filter(
        DocumentVersion.id == v2,
        DocumentVersion.document_id == document_id,
    ).first()

    if not ver1 or not ver2:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Version not found")

    lines1 = ver1.content.splitlines(keepends=True)
    lines2 = ver2.content.splitlines(keepends=True)

    diff = difflib.unified_diff(
        lines1, lines2,
        fromfile=f'v{ver1.version_number}',
        tofile=f'v{ver2.version_number}',
        n=3,
    )

    hunks = _parse_unified_diff(list(diff))

    return DocumentDiffResponse(
        v1=DocumentVersionWithContent(
            id=ver1.id,
            document_id=ver1.document_id,
            version_number=ver1.version_number,
            content=ver1.content,
            created_at=ver1.created_at,
            regeneration_reason=ver1.regeneration_reason,
        ),
        v2=DocumentVersionWithContent(
            id=ver2.id,
            document_id=ver2.document_id,
            version_number=ver2.version_number,
            content=ver2.content,
            created_at=ver2.created_at,
            regeneration_reason=ver2.regeneration_reason,
        ),
        hunks=hunks,
    )


def _parse_unified_diff(diff_lines: list[str]) -> list[DiffHunk]:
    """Parse unified diff output into a structured list of hunks."""
    hunks: list[DiffHunk] = []
    current_hunk = None

    for line in diff_lines:
        if line.startswith('---') or line.startswith('+++'):
            continue
        if line.startswith('@@'):
            if current_hunk is not None:
                hunks.append(current_hunk)
            match = re.match(r'@@ -(\d+),?(\d*) \+(\d+),?(\d*) @@', line)
            if match:
                current_hunk = DiffHunk(
                    old_start=int(match.group(1)),
                    old_count=int(match.group(2)) if match.group(2) else 1,
                    new_start=int(match.group(3)),
                    new_count=int(match.group(4)) if match.group(4) else 1,
                    lines=[],
                )
            continue
        if current_hunk is not None:
            if line.startswith(' '):
                current_hunk.lines.append(DiffHunkLine(type="context", content=line[1:]))
            elif line.startswith('+'):
                current_hunk.lines.append(DiffHunkLine(type="added", content=line[1:]))
            elif line.startswith('-'):
                current_hunk.lines.append(DiffHunkLine(type="removed", content=line[1:]))

    if current_hunk is not None:
        hunks.append(current_hunk)

    return hunks


@router.put("/{document_id}", response_model=DocumentResponse)
def update_document(
    document_id: int,
    body: DocumentUpdateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Update the content of an existing document."""
    # Fetch document
    document = db.query(Document).filter(
        Document.id == document_id,
        Document.owner_id == current_user.id
    ).first()
    
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )
    
    # Update content
    document.content = body.content
    db.commit()
    db.refresh(document)
    
    return document

@router.post(
    "/generate",
    response_model=DocumentResponse,
    status_code=status.HTTP_201_CREATED,
)
def generate_document(
    request: DocumentGenerateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Generate a compliance document for a user's AI system."""
    # Get the AI system
    ai_system = (
        db.query(AISystem)
        .filter(
            AISystem.id == request.ai_system_id, AISystem.owner_id == current_user.id
        )
        .first()
    )

    if not ai_system:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="AI system not found"
        )

    # Get template
    template = DOCUMENT_TEMPLATES.get(request.document_type)
    if not template:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"No template available for {request.document_type}",
        )

    # Get latest risk assessment if available
    from app.models.ai_system import RiskAssessment

    assessment = db.query(RiskAssessment).filter(
        RiskAssessment.ai_system_id == ai_system.id
    ).order_by(RiskAssessment.assessed_at.desc()).first()
    
    try:
        content = generate_compliance_narrative(
            document_type=request.document_type,
            ai_system=ai_system,
            risk_assessment=assessment,
            company_name=current_user.company_name
        )
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"LLM generation failed, falling back to template: {str(e)}")
        
        from datetime import datetime
        content = template.format(
            system_name=ai_system.name,
            version=ai_system.version or "1.0",
            use_case=ai_system.use_case or "Not specified",
            sector=ai_system.sector or "Not specified",
            description=ai_system.description or "No description provided",
            risk_level=ai_system.risk_level.value if ai_system.risk_level else "Not assessed",
            date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            company_name=current_user.company_name or "Not specified",
            classification_reasons="See risk assessment details",
            recommendations="Based on risk assessment",
            requirements="See applicable requirements above",
            next_steps="Complete all checklist items"
        )

    # Create document
    document = Document(
        owner_id=current_user.id,
        ai_system_id=ai_system.id,
        title=f"{request.document_type.value.replace('_', ' ').title()} - {ai_system.name}",
        document_type=request.document_type,
        status=DocumentStatus.GENERATED,
        content=content,
    )
    db.add(document)
    db.commit()
    db.refresh(document)

    return document


@router.delete("/{document_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_document(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Delete a document owned by the current user."""
    document = (
        db.query(Document)
        .filter(Document.id == document_id, Document.owner_id == current_user.id)
        .first()
    )

    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Document not found"
        )

    db.delete(document)
    db.commit()


@router.get("/{document_id}/pdf")
def export_document_pdf(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Export a document as a PDF attachment."""
    # Retrieve the document
    document = db.query(Document).filter(
        Document.id == document_id,
        Document.owner_id == current_user.id
    ).first()
    
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )
    
    if not document.content:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Document has no content to export"
        )
    
    # Generate PDF
    pdf_buffer = BytesIO()
    
    # Create PDF document
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=A4,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch,
    )
    
    # Container for PDF elements
    story = []
    
    # Get styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor='#1f2937',
        spaceAfter=12,
        alignment=TA_CENTER,
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=11,
        alignment=TA_LEFT,
        spaceAfter=12,
    )
    
    # Add title
    story.append(Paragraph(_escape_pdf_text(document.title), title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Add metadata
    metadata_style = ParagraphStyle(
        'Metadata',
        parent=styles['Normal'],
        fontSize=9,
        textColor='#6b7280',
        spaceAfter=12,
    )
    story.append(Paragraph(f"<b>Document Type:</b> {document.document_type.value}", metadata_style))
    story.append(Paragraph(f"<b>Status:</b> {document.status.value}", metadata_style))
    story.append(Paragraph(f"<b>Created:</b> {document.created_at.strftime('%Y-%m-%d %H:%M:%S')}", metadata_style))
    story.append(Spacer(1, 0.3*inch))
    
    # Process content - split by lines and handle markdown-like formatting
    content_lines = document.content.split('\n')
    for line in content_lines:
        if not line.strip():
            story.append(Spacer(1, 0.1*inch))
        elif line.startswith('# '):
            # Heading 1
            heading_style = ParagraphStyle(
                'CustomHeading1',
                parent=styles['Heading1'],
                fontSize=16,
                textColor='#1f2937',
                spaceAfter=12,
                spaceBefore=12,
            )
            story.append(Paragraph(_escape_pdf_text(line[2:]), heading_style))
        elif line.startswith('## '):
            # Heading 2
            heading_style = ParagraphStyle(
                'CustomHeading2',
                parent=styles['Heading2'],
                fontSize=13,
                textColor='#374151',
                spaceAfter=10,
                spaceBefore=10,
            )
            story.append(Paragraph(_escape_pdf_text(line[3:]), heading_style))
        elif line.startswith('### '):
            # Heading 3
            heading_style = ParagraphStyle(
                'CustomHeading3',
                parent=styles['Heading3'],
                fontSize=11,
                textColor='#4b5563',
                spaceAfter=8,
                spaceBefore=8,
            )
            story.append(Paragraph(_escape_pdf_text(line[4:]), heading_style))
        elif line.startswith('- '):
            # Bullet point
            story.append(Paragraph('• ' + _escape_pdf_text(line[2:]), body_style))
        else:
            story.append(Paragraph(_render_inline_markdown(line), body_style))
    
    # Build PDF
    doc.build(story)
    
    # Get PDF bytes
    pdf_bytes = pdf_buffer.getvalue()
    
    # Verify PDF is valid (starts with %PDF- magic bytes)
    if not pdf_bytes.startswith(b'%PDF-'):
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="PDF generation failed - invalid PDF format"
        )
    
    # Verify PDF is larger than 1KB
    if len(pdf_bytes) < 1024:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="PDF generation failed - PDF too small"
        )
    
    # Return PDF response
    filename = _safe_pdf_filename(document.title)
    return StreamingResponse(
        BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": (
                f'attachment; filename="{filename}"; '
                f"filename*=UTF-8''{quote(filename)}"
            )
        }
    )
